### ISSUE TITLE
Locale-install in makefile generates a Sandbox Violation in Gentoo

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#115]
This is strictly tied to Pull #109 as well as issue #29 ; Trying to write directly inside of the locale folder during the install phase generates a sandbox violation.

https://devmanual.gentoo.org/appendices/common-problems/index.html#handling-access-violations
https://devmanual.gentoo.org/general-concepts/sandbox/index.html

I'm attaching the build logs of the last test I made.
[logs.zip](https://github.com/EionRobb/purple-discord/files/1239863/logs.zip)

Thank you for your attention

**Comment by bobbybee** [comment]
According to https://wiki.gentoo.org/wiki/Localization/Guide locales are
stored in /usr/share/i18n/locales/ on Gentoo, as opposed to
/usr/share/locale which is the result of

	$(shell $(PKG_CONFIG) --variable=datadir purple)/locale`

in the Makefile.

I'm guessiing if you forced `$(LOCALEDIR)` to be the correct path for
Gentoo it should build and function correctly. (If it does, also check
what happens when the system is set to Spanish, i.e. by running `$
LANGUAGE=es pidgin`)

Assuming this is the case, we need a more robust way to detect locale
install locations.

(I imagine the build is broken on macOS etc for the same reason)

**Comment by EionRobb** [comment]
/usr/share/locale is the correct folder on gentoo, from memory the fix is that we need to add a $(PREFIX) to the install?

**Comment by bobbybee** [comment]
Hm okay. I'll let you two sort it out I guess :p

**Comment by Penaz91** [comment]
I think it's possible to make gentoo install the locales via ebuilds by
remaking the src_install function and using the "domo" feature, but we
would need a way to stop the makefile from writing into unsafe folders

Il 21/ago/2017 23:56, "Alyssa Rosenzweig" <notifications@github.com> ha
scritto:

**Comment by dequis** [comment]
Prefix LOCALEDIR with $(DESTDIR) just like DISCORD_DEST?

**Comment by Penaz91** [comment]
I think that would just create a locale dir in the image of the package, which will probably end up copying the locales in the wrong path.
I think the best option we have is making a patch (that will be applied via ebuild) which takes away the locale-install function from the makefile only on gentoo, and let gentoo itself handle the locale installation with "domo".

I'll do some experiments when I have some time.

**Comment by Penaz91** [comment]
Solved by pull #116
