### ISSUE TITLE
Handling channel categories

### ISSUE THREAD

**Issue by snackiz** [EionRobb/purple-discord#175]
Channel categories are shown as a chat in the buddy list, just like channels.
This means I can open a channel category in pidgin and send a message to it, but it does nothing on the server side, so the message just vanishes.

Either remove the categories from the buddy list or turn them into groups on the buddy list.

**Comment by alexolog** [comment]
Can this be looked into?

Also, prepending the category name to the channel name will help differentiate between identically named channels in different categories.

**Comment by MangaD** [comment]
Hello, I'd like to reopen this issue. I personally do not like the categories being shown in the buddy list, because a server with many categories will clutter the buddy list. The ideal would be to have the server as a group, and the categories as groups inside that group. I deduce that is not possible? Perhaps this feature should be requested from the Pidgin developers?

**Comment by EionRobb** [comment]
@MangaD libpurple doesn't provide that ability to nest groups (and there's more than just Pidgin as a UI that would need to support it), so we're doing as much as we can at the moment with the API that's there.

**Comment by MangaD** [comment]
Have you considered opening an issue at libpurple for it to provide this feature? Thank you for all your work!
