### ISSUE TITLE
In group chats, sending a message which has a colon in it crashes pidgin

### ISSUE THREAD

**Issue by user234683** [EionRobb/purple-discord#180]
More specifically, a colon which isn't part of a link, and only in group chats. For instance, the message "test: fwefwef" crashes pidgin when sent to a group. If the group chat is set to auto-join, pidgin will also crash with a "Microsoft Visual C++ Runtime Error" like in #161 when attempting to restart it until you disable the auto-join. Rejoining after doing so will not crash. The message is not actually sent to the group and is not logged.

Some further testing reveals exactly what kinds of messages will cause a crash.
-The colon MUST have a space after it
-There must be a character, any character, before the colon.
Nothing else matters besides that

Here is the crash info:
```
  Problem Event Name:	APPCRASH
  Application Name:	pidgin.exe
  Application Version:	2.12.0.0
  Application Timestamp:	58c20b6e
  Fault Module Name:	libdiscord.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a188e28
  Exception Code:	c0000005
  Exception Offset:	00003d45
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
```

**Comment by bobbybee** [comment]
Sounds like a bug in the mention handling code.

**Comment by bobbybee** [comment]
I can reproduce this. Investigating...

**Comment by EionRobb** [comment]
@user234683 if you can attach the last crash from %appdata%\.purple\Pidgin.RPT too

**Comment by bobbybee** [comment]
I have a patch to fix it ;)

**Comment by bobbybee** [comment]
From 54ab2886bdf082fecb9a89fe6531917286afdd8c Mon Sep 17 00:00:00 2001
From: Alyssa Rosenzweig <alyssa@rosenzweig.io>
Date: Sun, 13 May 2018 00:44:58 +0000
Subject: [PATCH] Fix null dereference in group chats, close #180

When sending a messgae "like: this", the mention regex handler attempts
to find the entity named "like". If the user does not exist, in
multi-user chats, it instead searches for various guild entities.
However, in a group chat (rather than a server), there is no guild.
Accordingly, guild can be NULL in this handler, leading to crashes as
described in #180.

By adding checks to ensure `guild` is non-NULL, the crash is eliminated,
and the message is sent accordingly.

Thank you to James Taylor for reporting.

Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>
---
 libdiscord.c | 7 +++++++
 1 file changed, 7 insertions(+)

diff --git a/libdiscord.c b/libdiscord.c
index ec18df2..5a7627f 100644
--- a/libdiscord.c
+++ b/libdiscord.c
@@ -1413,6 +1413,9 @@ discord_replace_mentions_bare(DiscordAccount *da, DiscordGuild *g, gchar *messag
 static guint64
 discord_find_role_by_name(DiscordGuild *guild, const gchar *name)
 {
+	if (!guild)
+		return 0;
+
 	if (purple_strequal(name, "everyone")) {
 		return guild->id;
 	}
@@ -1438,6 +1441,10 @@ discord_find_channel_by_name(DiscordGuild *guild, gchar *name)
 	GHashTableIter iter;
 	gpointer key;
 	gpointer value;
+
+	if (!guild)
+		return 0;
+
 	g_hash_table_iter_init(&iter, guild->channels);
 
 	while (g_hash_table_iter_next(&iter, (gpointer *) &key, &value)) {
-- 
2.17.0

**Comment by EionRobb** [comment]
This crash also happens when trying to mention someone in a multi-user chat (instead of a guilded channel)

**Comment by EionRobb** [comment]
@user234683 If you want to give https://eion.robbmob.com/libdiscord.dll a try and see if it still happens

**Comment by EionRobb** [comment]
https://github.com/EionRobb/purple-discord/commit/892599fbe8f9dc8616a0959eae235e627e224bab was the commit using a slightly modified version of @bobbybee 's patch

**Comment by user234683** [comment]
@EionRobb I can confirm the bug is fixed with that module.
