### ISSUE TITLE
High CPU and RAM usage in combination with Spectrum2

### ISSUE THREAD

**Issue by mbirth** [EionRobb/purple-discord#251]
I'm using purple-discord together with Spectrum2 and ejabberd on a Raspberry Pi 3B+.

I'm also using purple-facebook, purple-hangouts and purple-telegram. Those other transports work fine, but as soon as I enable purple-discord, my Raspberry Pi's CPU usage goes up to 100% for several minutes and then settles at around 10% for the `spectrum2_libpurple_backend` for Discord alone with it also eating up 25% of the 1GB RAM.

The other `spectrum2_libpurple_backend` processes for Telegram, Hangouts and Facebook are at much lower values with almost no CPU usage (0.0-0.1%) and around 1.2-1.5% RAM usage.

What's happening here?

**Comment by EionRobb** [comment]
There's a lot of user/channel/server state that we have to store client-side as the server assumes that the client knows about such things (probably as a way of cutting down on server processing) - so that eats up a fair bit of RAM, especially when connected to servers with a lot of users

The CPU usage can be high due to the constant sending of status changes that get broadcast from every user on every server that you're connected to.  The plugin also uses Gzip compression for the websocket stream to reduce network usage, at the expense of CPU usage.

It sounds like your user is connected to one or more servers with lots of users connected to them.   If you want to email through a purple debug log from spectrum2, I'd be happy to give any recommendations I can in order to reduce memory/CPU usage

**Comment by EionRobb** [comment]
You can disable the gzip compression to save some CPU cycles (at the expense of network bandwidth) by enabling the (hidden) "disable-compress" setting in ~/.purple/accounts.xml

Otherwise, feel free to reopen this issue if you can find something else that might pinpoint what's going on.  The offer to review your debug logs is always open too.

**Comment by mbirth** [comment]
Thanks a lot! Is there any way to disable the general chat stuff and only use this plugin for direct messages?

**Comment by EionRobb** [comment]
Sure, you can turn off the "auto-create rooms on buddy list" and "open chat when you are @mention'd" settings, and just use it for IM's

**Comment by mbirth** [comment]
Hmm ... I've set 

```
<account version='1.0'>
        <account>
                <settings>
			<setting name='populate-blist' type='bool'>0</setting>
			<setting name='open-chat-on-mention' type='bool'>0</setting>
```

in `accounts.xml` but it doesn't seem to get picked up. The transport is still using a third of all RAM and CPU is going crazy. Or do these options don't change the bookkeeping of all the server stuff?

**Comment by EionRobb** [comment]
No, the server still sends *everything*

**Comment by mbirth** [comment]
And purple-discord processes that? Or does it drop the stuff it doesn't need?

**Comment by EionRobb** [comment]
It drops the stuff it doesn't need, but it still has to process it to know what to keep.  For example, we need to keep a record of every user on every server you're connected to, in case one of them DM's you via a server.

**Comment by mbirth** [comment]
Just for the record: On a Raspberry Pi 4 with 4GB RAM, the CPU usage is around 2% with RAM usage being around 6.5% (=25% of 1GB) for me. Technically the same as before, but not nearly as dramatic on this more powerful board.
