### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#29]
Great job with this plugin, I just found it and it works wonders, and I want to contribute in the only way I can.
I'm a gentoo user and I wrote a simple Ebuild that can be tested by other gentoo users.

To use the ebuild:
1. Copy it to "/usr/local/portage/x11-plugins/purple-discord" (creating the folders if necessary)
2. Run `ebuild purple-discord-9999.ebuild manifest`
3. If eix is installed, run `eix-update; eix-diff`

Now the plugin should be able to be installed with `emerge purple-discord`.

If this works well, I could request the Gentoo team to include the ebuild in portage.

Hope it helps a bit.
[ebuild.zip](https://github.com/EionRobb/purple-discord/files/994369/ebuild.zip)

**Comment by EionRobb** [comment]
Awesome :)

You could probably add ~* to keywords (is that how that works) since it's not arch-dependant code, and could run on arm or ppc.  Also, would be good to throw in that it depends on glib-2.0

I'm not sure where the best place for this to live is.  Possibly your idea of filing a bug with Gentoo to include that ebuild?

**Comment by Penaz91** [comment]
I added all the archs possible (using * is deprecated, and -* means "binary package"), and I think a bug on gentoo bugzilla is the right way to see if the ebuild is accepted.

Here is the updated version.
[ebuild.zip](https://github.com/EionRobb/purple-discord/files/998452/ebuild.zip)

**Comment by Penaz91** [comment]
I took the liberty to post a bug on Gentoo, featuring the latest ebuild that I posted.

Hope that's okay with you.
