### ISSUE TITLE
purple2compat: missing COPYRIGHT file, information about code origins?

### ISSUE THREAD

**Issue by pabs3** [EionRobb/purple-discord#325]
The new `purple2compat/` directory appears to have been directly imported from another project but the COPYRIGHT file referred to by the copyright headers in each of the `.c` files is missing. Also it would be nice to have a README with some information about where the code came from and how to update the copy of the code. I see some other users of this code on GitHub but I haven't been able to find the original project.

**Comment by EionRobb** [comment]
Huh, sorry about the license stuff!  That's not good. :(

Bit of a story to that code: the purple2compat folder originally comes from the [purple-hangouts](https://github.com/EionRobb/purple-hangouts/) plugin and written by maiku, but most of the original code comes from purple3 (before it removed it's own http code and relied on libsoup, which isn't compatible with WinPidgin due to the newer glib requirement) but then has some glue-code to make it work with purple2's eventloop since purple3 relied on gio

**Comment by pabs3** [comment]
I think it would be a good idea to split the purple2compat code out into a library that could be shared between multiple plugins, so that all the needed changes can be made in one place. Another better option would be to merge into libpurple upstream to make it easy for plugins to be ported to libpurple3.

**Comment by pabs3** [comment]
Getting this sorted out is a blocker to updating the Debian package, so it would be great if it could get completed.

**Comment by EionRobb** [comment]
Thanks for following up with this.  The  COPYRIGHT file from libpurple has been added to the purple2compat folder in https://github.com/EionRobb/purple-discord/commit/d9c4c08a70168239131e3469a6e8da57b8e1d2f3

In terms of the other nice to haves (splitting out code, adding a readme) are they blockers to getting the Debian package out?

**Comment by pabs3** [comment]
That seems like enough for getting this into Debian, thanks.

I do still think the best place for this is in the libpurple codebase, or possibly a shared library.

Shall we close this issue and open a new one for where to store the purple2compat codebase?

**Comment by EionRobb** [comment]
The code used to be in purple3 but was removed in favour of libsoup (but that's too new for the version of glib that pidgin2 ships with on windows)

Probably be best in a new shared lib, yeah 

Let's close this one off for now :)
