### ISSUE TITLE
Discord Account Disabled for Suspicious Activity

### ISSUE THREAD

**Issue by chainria** [EionRobb/purple-discord#363]
I got this TWICE over a weekend now. I really don't know how they track it, but unfortunately it seems they are literally banning this plugin. I don't know what to do other than just not use it for now. Has anyone else had this problem recently?

**Comment by Princess-Luna-at** [comment]
I got the same problem. Right now i git deactivated a secind time. I wrote the support now maybe they provide some helpfull ingormation, but I my guess was it might be the plugin too.

**Comment by chainria** [comment]
I updated the plugin to master again and will try a third and last time, let's see if it works out. If not, I'll wait before they suspend it any further.

**Comment by svip** [comment]
I have also received this message, even though I am using another plugin: https://github.com/sm00th/bitlbee-discord

But I know they both use the `token` trick.  I assumed because the two clients (the Discord and mine) did not originate from the same IP address, that that's how they detected it.  Which I could see as potentially suspicious activity, unfortunately, their email provided no way of insisting it was all right.

I did read elsewhere that Discord is phasing out their old API in favour of a new API: https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1

It seems like a lot of alternative ways to connect to Discord are about to be disabled in the coming future.

**Comment by chainria** [comment]
Guess it's time to backup my messages again!

**Comment by chainria** [comment]
Unfortunately, this happened again. Which means I won't be using this plugin for now. My account is really precious to me, but I have a secondary one I am willing to use for testing. After all, I really want to be able to use this plugin.

**Comment by zmike** [comment]
I've hit this as well.

**Comment by Schmaiffe** [comment]
I got hit with this three times on my main (which is logged in with both Pidgin and on iOS) and once on my alt, which is logged in only on Pidgin. It seems to be happening like once a day now.

**Comment by EionRobb** [comment]
Can people report the versions of the Discord plugin they're getting this with?  From the buddy list, Help->Plugin Information, and then scroll down about half way, eg
![image](https://user-images.githubusercontent.com/1063865/132414610-eaea2ed7-cab1-444d-a4cd-b328cc9d68c5.png)

For the people who have contacted me directly about it, they're using a version from last year (Version: 0.9.**2020**...) which still broadcast itself as Pidgin, however as of https://github.com/EionRobb/purple-discord/commit/02c88dbf8eb1bc9e3822149199e5149a2df08625 in May we switched to looking like a regular chrome web browser

**Comment by Princess-Luna-at** [comment]
![Bildschirmfoto_2021-09-07_23-46-53](https://user-images.githubusercontent.com/81704603/132415195-68844d7d-fb9d-45b0-bac0-88ea1f1025f4.png)

Here you go, i disabled it for now and the account suspension stopped..

**Comment by chainria** [comment]
Here you go! Like I mentioned, I updated to master (I am using the 9999 Gentoo Ebuild). Was indeed using some older build, but even with master this happened twice.

![image](https://user-images.githubusercontent.com/4046580/132415856-1d352f98-2a28-43b7-bb43-7db4762bf0b8.png)

**Comment by Jach** [comment]
I had this happen on Sunday (9/5) and again this morning, currently trying the support route.. On Sunday I updated from whatever version was the latest in July to whatever was latest on Sunday.
![image](https://user-images.githubusercontent.com/159184/132417192-65e187d9-d354-4613-9ae2-88eb92f7bf11.png)

**Comment by EionRobb** [comment]
Alrighty, so not fixed in recent versions.  Thanks everyone for the screenshots :)

I noticed that we're saying we're both old versions and new versions of Chrome which might have tripped something, but that's changed in https://github.com/EionRobb/purple-discord/commit/d70740890947fecff9abec969339aa8be080d47b if you want to try with a newer version of the dll/git

Unfortunately I haven't been stung by this yet, so I'm not able to work out what might be tripping it.

**Comment by alexolog** [comment]
I got it once several days ago when I took the laptop on a trip.  It usually connects from the home wifi, but this time it was tethered from the phone data.  I also had the desktop at home still connected.

Trying to connect from the browser got me an email with a link to click, after I did, and logged in from the browser, everything continued working as before.

**Comment by adrianmalacoda** [comment]
I am running 6c5a778 from 29 July and have not yet encountered this issue. I am running the proprietary client and this plugin (under Bitlbee, not Pidgin, if that matters) on different machines both connected to the same network, and have no other clients connected to Discord anywhere else.

**Comment by EionRobb** [comment]
Just to try work out a common cause, can peoples who have had their account suspended for suspicious activity please react to this comment with:

- Thumbs up 👍  I *do* use 2FA and my account was suspended
-  or thumbs down 👎 I *do not* use 2FA and my account was suspended

someone in #pidgin on librachat suggested that turning on 2FA might help prevent the suspensions

**Comment by chainria** [comment]
I have my second account dug out now and am using it with the old (unpatched) version in order to trigger the account lockdown. Fun fact? It just worked, no funny Captcha business and no digging for any Tokens. It just works (TM). Maybe it's the fact that this account does **not** use any 2FA? I really don't know.

**Comment by alexolog** [comment]
The account that I am using was at one time flagged and could only be reinstated by adding a phone number.  I do not use 2FA though.

**Comment by katajanmarja** [comment]
I've triggered this twice within 3 days this month, not using 2FA, have verified with phone earlier, generally have it open BOTH on the browser and in Pidgin simultaneously. Version 0.9.2020.04.05.git.db7dc79-1. (Left account disabled on Pidgin for now and triggers stopped.)

**Comment by EionRobb** [comment]
Comments from people suggesting that its only triggering after a long time got me thinking. It looks like the websocket connection restarts every 4 or 5 minutes now whereas beforeit would stay connected for as long as possible, several days of needed. 

I'll try adding in a periodic reconnection to see if that helps.

**Comment by chainria** [comment]
Right now nothing has happened with my second account, but it's only sitting there, idling. This account is not really known to anyone, I only use it for development away from my main one. Maybe it's really something like that long period. I will keep it running like this until I notice anything out of the ordinary.

**Comment by Schmaiffe** [comment]
This has now happened four times to my main, twice to my alt. It seems to be a daily event now. I have been talking with Discord's support, and they're giving me the runaround, not admitting that there's a problem. Main is logged in on both Windows/Pidgin and on the official iOS app, alt is only logged in on Windows/Pidgin. Each time it happens, I change my password and log back in. No more permanent action has been taken against my account.

I don't have 2FA on either account.

A weird thing happened too when this started. Right after I first reset my password and logged back in, it's been ignoring muted status on various servers/channels, and opening new windows at random. They look pretty bad--I don't have them on my buddy list or anything, so they just pop up constantly, with the chat name as a random number, with some comment with absolutely no context. I already have the servers/channels muted, so I have no idea how else to turn them off. It wasn't doing this until the first time my account was disabled for suspicious activity.

**Comment by Schmaiffe** [comment]
It happened a fifth time to my main, and a third time to my alt. Support, after repeatedly gaslighting me that my account was being accessed by an unauthorized user (they told me they "did an investigation," when I know it's literally impossible that my account is being hacked with unique passwords on a daily basis and this is coincidentally happening to other third-party client users just this week. When I kept pressing that, they told me third party clients are against the TOS, and they have no power to help me with it. Also told me to turn on 2FA, which I see no reason to do since other users in this thread have 2FA and have been hit?

I wasn't even logged in on Pidgin for most of the day. I was up till around 3 AM, then turned my computer off and didn't turn it on again until 2 PM. When I turned it on, I'd already been shadowbanned again, on both accounts. So it seems to be checking once a day to see if I've used a third-party client any time during that day, and doing the password reset thing once a day based on that. The emails informing me of it from today were at 1:33 and 1:40. (All EST.) From yesterday, 3:08 and 3:16. From the day before yesterday, 2:10 and 2:19. Before that, it was only on my main and every two days instead of every day, with the times more random. But now it seems to be striking every day, even if I haven't logged in at all in nearly 12 hours, some time around early afternoon EST.

**Comment by alexolog** [comment]
This is strange.  It does not happen on my desktop at all, and only happened on the laptop once when I was tethering it to my phone, but not after that.  Not sure how my setup is different.

**Comment by katajanmarja** [comment]
@alexolog could be related to different connectivity, if EionRobb's suspicion of the reconnect effect is on the right track. If the phone connection was more unstable, you'd potentially get more sudden disconnects, and could seem more suspicious than usual as a result.

(Another cause to trigger behaviour like that could be indirectly related to where you connect from, if you share the IP address with other suspicious users when connecting through the phone network and haven't happened to hit the naughty list with the house network address space. But Discord doesn't seem to flag directly on IP address, or even connecting from different locations as such, but some slightly more complex behaviour pattern.)

**Comment by alexolog** [comment]
And just like that, I got the account disabled right now.
Bummer

**Comment by LittleVulpix** [comment]
I'm using a different 3rd party client and I've gotten my account disabled 5 times. It happens at random, but pretty much every day now. Not doing anything stupid or crazy, not joined in many guilds or anything like that. Sadness. I'll be watching this issue with great interest.

**Comment by alexolog** [comment]
I know that the Discord protocol is very chatty, even when nothing is going on.  Could it be that the server implemented some sort of a new challenge/response mechanism that is triggered every now and then?

It will be a pain to find though.  Will probably require continuous logging until it happens.

**Comment by chainria** [comment]
My primary account, which I don't use with the plugin anymore (which actually is a REAL hassle!) did not get flagged again. My secondary account, which is online all the time with the plugin, does not get flagged either. I am still on the version of my screenshot, so  guess it is neither the mixed versions nor some strange issue with the plugin itself. The only suspicion I have is that the plugin must actually transmit data (like real conversations) to get noticed.

**Comment by LurkerHub** [comment]
Happens to me as well.

Thing is, Discord has become *the* platform for social chatting.
Out of 53 buddies in Pidgin, only 6 are not on Discord.
And that does not even count the servers/channels/rooms that a large part of my communication happens on.
All in all, I'd say that my use of Pidgin is 95% Discord and I often find myself just using the Discord client for features that Pidgin does not support.

If my usage is anywhere close to representative, working Discord support is important to many people.

**Comment by Schmaiffe** [comment]
Got my daily shadowban, this is now 6 times on my main, 4 times on my alt. At 2:04 PM and 2:05 PM EST. It's really like clockwork now.

**Comment by alexolog** [comment]
Thanks @EionRobb !

**Comment by xogium** [comment]
I've been doing tests with bitlbee here as well, and so far this is the most promising test I ever ran.

I connected to discord and left it hanging there. I did not "join" any chat channels in bitlbee, I simply connected and left it there. I did not receive any pm or sent any.

I've now gotten up to 3 days without being kicked out this way. So I joined one chat, but did not say anything.

If this hold for another 2 or 3 days more, I will send just a hello message to that channel, and somehow I bet as soon as I do this they will target me in their next run of whatever kicks us out.

I'll update this comment to let y'all know what happens.

**Comment by chainria** [comment]
Still nothing new from my front. I think I will join some servers just for shits and gigles and idly sit there. I think not doing anything (active nor passive) is flying under the radar. Maybe this changes if I go to some active servers so the client actually communicates (even passively)

**Comment by erkinalp** [comment]
as jhgg said in https://news.ycombinator.com/item?id=25224151:

> We are not banning people for using Ripcord. We are banning people for using our API in ways that our official client doesn't. This is paramount to our spam detection strategy, which is detecting quirks in requests that try and emulate our official client, in order to send spam. There is a very thin line between "scripts meant to try and emulate our client to send spam in an automated fashion" and "third party client" both try and emulate our client, but perhaps for different intent. However, our systems currently treat these as equals. It is for this reason that we have maintained that 3rd party clients are against our ToS - and most warn you before you use them. Given the vanishingly small user-base of 3rd party clients relative to the tremendous amount of spam-bots that constantly are attacking our platform, it's an unfortunate reality that this is bound to happen.
> 
> If you are a real human, and not a spam bot, our general policy is to unban and tell you "hey don't do that again." Which is the outcome that should have (and eventually did) happened here.

**Comment by erkinalp** [comment]
> I did read elsewhere that Discord is phasing out their old API in favour of a new API

No, they are going to require whitelisting of bots that read others' messages, otherwise using the same endpoints.

**Comment by Schmaiffe** [comment]
Interestingly, I did *not* get a ban yesterday. I did whine about it on their public feedback forum, but I only did that with my main, not my alt, and neither received a ban yesterday. I haven't updated Pidgin, enabled 2FA, or done anything differently. It's possible they're fixing this issue on their end? I also wonder if they're just not running whatever their thing is on the weekend and will ban me again on Monday. Guess we'll wait and see.

Considering I did nothing different (still sending and receiving messages at the same rate I did before) and had been getting daily bans on two accounts like clockwork for several days in a row, just wanted to caution that whatever seems to be working for you guys might be coincidence, because it stopped for me too.

**Comment by LittleVulpix** [comment]
> 
> 
> I tried doing a 48 hour capture to see if anything unusual happens every so often with the official web client in order to imitate but nothing has popped out yet. In the meantime, I've added in a 5 minute reconnect, as that's what the web client seems to be doing. Hoping it helps people out :(

Did this iomprove the situation?

**Comment by EionRobb** [comment]
> > I tried doing a 48 hour capture to see if anything unusual happens every so often with the official web client in order to imitate but nothing has popped out yet. In the meantime, I've added in a 5 minute reconnect, as that's what the web client seems to be doing. Hoping it helps people out :(
> 
> Did this improve the situation?

I think it was just coincidental timing that it looks like it improved.

Other third party Discord clients have had similar issues over the past week, and it looks like their users have also reported that they haven't been disabled in the past couple of days.  I'm crossing my fingers that whatever anti-spam detection thing that Discord had implemented, they decided to roll-back on.

Dealing with IM spam (aka SPIM) is definitely not a new problem that they're trying to solve, but trying to block clients that don't behave exactly like their regular web/desktop/mobile client is a.... well, lets just say that's the first time I've seen anyone do it that way (and I've _[seen things](https://www.nplusonemag.com/issue-19/essays/chat-wars/)_)

**Comment by LittleVulpix** [comment]
> 
> 
> > > I tried doing a 48 hour capture to see if anything unusual happens every so often with the official web client in order to imitate but nothing has popped out yet. In the meantime, I've added in a 5 minute reconnect, as that's what the web client seems to be doing. Hoping it helps people out :(
> > 
> > 
> > Did this improve the situation?
> 
> I think it was just coincidental timing that it looks like it improved.
> 
> Other third party Discord clients have had similar issues over the past week, and it looks like their users have also reported that they haven't been disabled in the past couple of days. I'm crossing my fingers that whatever anti-spam detection thing that Discord had implemented, they decided to roll-back on.
> 
> Dealing with IM spam (aka SPIM) is definitely not a new problem that they're trying to solve, but trying to block clients that don't behave exactly like their regular web/desktop/mobile client is a.... well, lets just say that's the first time I've seen anyone do it that way (and I've _[seen things](https://www.nplusonemag.com/issue-19/essays/chat-wars/)_)

That was a very amusing read! Thank you for that.

And I don't want to derail this issue discussion into a forum so I'll just mention that I get the whole spam thing, but they could just implement it if someone is doing something actually bad (like sending a bunch of bad messages etc), instead of going against literally all the clients. My client is not popular at all and yet it is being blocked exactly the same way - and I don't use it in abusive manner, I literally use it because I can't stand "electron" website-applications.

I'll keep track of this topic to see if/when it becomes OK to start using 3rd party clients and/or what needs to be done to facilitate that.

**Comment by Schmaiffe** [comment]
No problems all weekend or on Monday, on either main or alt. I'm kind of the perfect control because I have done literally nothing differently, haven't updated anything, have exchanged messages on both accounts daily, and still don't have 2FA on either. It seems the ban on third party clients wasn't intentional and they fixed whatever was flagging them? In any case, I'm glad it doesn't seem to be happening anymore, and also that they aren't intentionally trying to go after third-party clients.

**Comment by alexolog** [comment]
3p clients are likely not even a blip on their radar now given the functionality gap and number of users.
But if they come up with a scheme that catches 50% of spambots but kills 100% of 3rd-party clients as collateral damage, they won't give it a second thought.

**Comment by erkinalp** [comment]
> catches 50% of spambots but kills 100% of 3rd-party clients

Swap that for 98% and 99.9%, or 50% or 67% respectively.

**Comment by alexolog** [comment]
It was a hypothetical

**Comment by erkinalp** [comment]
I just provided more statistically accurate figures that would match some sort of receiver response curve.

**Comment by LittleVulpix** [comment]
Since nobody is posting here I assume the issue may have gone away? I saw someone else posting somewhere that whatever measures were put in, were again disabled for now.

**Comment by EionRobb** [comment]
Lets go with that

If things start getting bad again then we'll open a new ticket :)
