### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#91]
Can you please explain the 3 options on the "advanced" tab and what they affect?

**Comment by bobbybee** [comment]
Use status message as in-game info: If set, the status message set via
Pidgin (the text under Available, Away, etc in the buddy list) will be
used as the game info for Discord "Playing ...". I think this may be
broken right now.

Auto-create rooms on buddy list: If set, the plugin will add the
channels (rooms) from the servers you're on as chats on your buddy list.
This is preferred if you're using Pidgin, so you don't need to access
the room list manually. If you're not using Pidgin (or finch), you
probably don't want this, since they have different buddy list APIs.
Note: If the room list changes, it won't recreate the list unless you
delete the entire group.

Number of users in a large channel: Mention behaviour is "smart" in
here. If you're in a small channel, every time a message is sent, you'll
be notified and the channel will pop up. If you're in a large channel,
you'll only be notified if you're explicitly mentioned in the message.
This value is the threshold to define a large channel. By default, if
there are more than 80 (online) users in the channel, it will be
considered large.

**Comment by EionRobb** [comment]
@bobbybee great write-up.  I might add that to the Readme.md

**Comment by EionRobb** [comment]
https://github.com/EionRobb/purple-discord/commit/3dc29f35e5b55cf20fcfec328e6001f79b7974fa how bow dat?
