### ISSUE TITLE
both alias and user-id are displayed

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#98]
Displaying "alias (user#number)" takes too much screen space.
For example: moderately long alias (moderately long alias#12345)

Can this be configurable?

**Comment by bobbybee** [comment]
(This is a known issue that's on the invisible TODO list)

This isn't configurable... it's a result of buggy behaviour; I think everyone would like it fixed :)

The issue occurs when the connection is refreshed and nicknames are reallocated. Since the old nickname tables are still in memory, the client thinks every username is a duplicate, so it expands it out completely to resolve the collision. The most obvious way to handle this is to check if the users are identical when allocating nicknames.
